export const SET_USERS = "SET_USERS";
export const AUTH_USER = "AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CHANGE_REGISTRATION_FIELD = "CHANGE_REGISTRATION_FIELD";
export const CHANGE_REGISTRATION_FIELD_ERROR = "CHANGE_REGISTRATION_FIELD_ERROR";