export const SET_USERS = "SET_USERS";
export const AUTH_USER = "AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CHANGE_MYACCOUNT_FIELD = "CHANGE_MYACCOUNT_FIELD";
export const GET_MYACCOUNT = "GET_MYACCOUNT";
