const message = {
    'en': {
        'header': 'Welcome',
        'search': 'Search ...',
        'language': 'Language:',
        'theme': 'Theme:',
        'light': 'light',
        'dark': 'dark',
        'notifications': 'Notifications:',
        'reset': 'Reset all settings',
        'newLogin': 'New login',
        'newPassword': 'New password',
        'confirmPassword': 'Confirm password',
        'newLoginPlaceholder': 'Enter your new login...',
        'newPasswordPlaceholder': 'Enter your new password...',
        'repeatPasswordPlaceholder': 'Repeat your new password...',
        'confirmBTN': 'Confirm',
        'createBTN': 'Create',
        'cancelBTN': 'Cancel',
        'roomName': 'Room name',
        'roomNamePlaceholder': 'Enter name your new room...',
        'addMembers': 'Who do you want to add',
        'addAll': 'all',
    },
    'ru': {
        'header': 'Добро пожаловать',
        'search': 'Поиск ...',
        'language': 'Язык:',
        'theme': 'Тема:',
        'light': 'Светлая',
        'dark': 'Темная',
        'notifications': 'Уведомления:',
        'reset': 'Cбросить все настройки',
        'newLogin': 'Новый логин',
        'newPassword': 'Новый пароль',
        'confirmPassword': 'Подтвердите пароль',
        'newLoginPlaceholder': 'Введите новый логин...',
        'newPasswordPlaceholder': 'Введите новый пароль...',
        'repeatPasswordPlaceholder': 'Подтвердите новый пароль...',
        'confirmBTN': 'Подтвердить',
        'createBTN': 'Создать',
        'cancelBTN': 'Отменить',
        'roomName': 'Название комнаты',
        'roomNamePlaceholder': 'Введите название комнаты...',
        'addMembers': 'Кого вы хотите добавить',
        'addAll': 'всех пользователей',
    },
    'ar': {
        'header': 'أهلا بك',
        'search': 'بحث'
    }
}
export default message;
