const message = {
    'en': {
        'header': 'Welcome',
        'search': 'Search ...',
        'language': 'Language:',
        'theme': 'Theme:',
        'light': 'light',
        'dark': 'dark',
        'notifications': 'Notifications:',
        'reset': 'Reset all settings',
        'newLogin': 'New login',
        'newPassword': 'New password',
        'confirmPassword': 'Confirm password',
        'newLoginPlaceholder': 'Enter your new login...',
        'newPasswordPlaceholder': 'Enter your new password...',
        'repeatPasswordPlaceholder': 'Repeat your new password...',
        'confirmBTN': 'Confirm',
        'createBTN': 'Create',
        'saveBTN': 'Save',
        'cancelBTN': 'Cancel',
        'roomName': 'Room name',
        'roomNamePlaceholder': 'Enter name your new room...',
        'addMembers': 'Who do you want to add',
        'addAll': 'all',
        'firstName': 'First name',
        'lastName': 'Last name',
        'age': 'Age',
        'city': 'City',
        'companyName': 'Company name',
        'hobby': 'Hobby',
        'firstNamePlaceholder': 'Enter your first name...',
        'lastNamePlaceholder': 'Enter your last name...',
        'agePlaceholder': 'Enter your age...',
        'cityPlaceholder': 'Enter your city...',
        'companyNamePlaceholder': 'Enter your company name...',
        'hobbyPlaceholder': 'Enter your hobby...',
    },
    'ru': {
        'header': 'Добро пожаловать',
        'search': 'Поиск ...',
        'language': 'Язык:',
        'theme': 'Тема:',
        'light': 'Светлая',
        'dark': 'Темная',
        'notifications': 'Уведомления:',
        'reset': 'Cбросить все настройки',
        'newLogin': 'Новый логин',
        'newPassword': 'Новый пароль',
        'confirmPassword': 'Подтвердите пароль',
        'newLoginPlaceholder': 'Введите новый логин...',
        'newPasswordPlaceholder': 'Введите новый пароль...',
        'repeatPasswordPlaceholder': 'Подтвердите новый пароль...',
        'confirmBTN': 'Подтвердить',
        'createBTN': 'Создать',
        'saveBTN': 'Сохранить',
        'cancelBTN': 'Отменить',
        'roomName': 'Название комнаты',
        'roomNamePlaceholder': 'Введите название комнаты...',
        'addMembers': 'Кого вы хотите добавить',
        'addAll': 'всех пользователей',
        'firstName': 'Имя',
        'lastName': 'Фамилия',
        'age': 'Возраст',
        'city': 'Город',
        'companyName': 'Место работы',
        'hobby': 'Увлечения',
        'firstNamePlaceholder': 'Введите ваше имя...',
        'lastNamePlaceholder': 'Введите вашу фамилию...',
        'agePlaceholder': 'Введите ваш возраст...',
        'cityPlaceholder': 'Введите ваш город...',
        'companyNamePlaceholder': 'Введите ваше место работы...',
        'hobbyPlaceholder': 'Введите ваши увлечения...',
    },
    'ar': {
        'header': 'أهلا بك',
        'search': 'بحث'
    }
}
export default message;
